# Generated by Django 6.0.3 on 2026-03-06 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('overpaid', 'Overpaid')], default='paid', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_charged_at', models.DateTimeField(blank=True, null=True)),
                ('last_paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_type', models.CharField(choices=[('charge', 'Charge'), ('payment', 'Payment')], max_length=20)),
                ('cycle_number', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vishi.collectionledger')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vishi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('half_monthly', 'Half Monthly'), ('monthly', 'Monthly'), ('halfyear', 'Half Yearly'), ('yearly', 'Yearly')], max_length=20)),
                ('draw_day', models.PositiveSmallIntegerField()),
                ('collection_day', models.PositiveSmallIntegerField()),
                ('release_day', models.PositiveSmallIntegerField()),
                ('current_draw_date', models.DateField()),
                ('current_collection_date', models.DateField()),
                ('current_release_date', models.DateField()),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('current_cycle', models.PositiveIntegerField(default=0)),
                ('total_cycles', models.PositiveIntegerField(default=0)),
                ('missed_cycles', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vishis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vishis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='collectionledger',
            name='vishi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='vishi.vishi'),
        ),
        migrations.CreateModel(
            name='VishiParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vishi_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_drawn', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to=settings.AUTH_USER_MODEL)),
                ('vishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='vishi.vishi')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddField(
            model_name='vishi',
            name='fix_draw_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_draw_vishi', to='vishi.vishiparticipant'),
        ),
        migrations.AddField(
            model_name='collectionledger',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='vishi.vishiparticipant'),
        ),
        migrations.CreateModel(
            name='VishiDrawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField()),
                ('was_fixed', models.BooleanField(default=False)),
                ('drawn_at', models.DateField()),
                ('is_released', models.BooleanField(default=False)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('released_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_records', to='vishi.vishi')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draw_records', to='vishi.vishiparticipant')),
            ],
            options={
                'ordering': ['cycle_number'],
                'unique_together': {('vishi', 'cycle_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='collectionledger',
            unique_together={('vishi', 'participant')},
        ),
    ]
