# Generated by Django 6.0.3 on 2026-03-07 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vishi',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.CreateModel(
            name='SkipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skipped_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('is_auto', models.BooleanField(default=False)),
                ('vishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip_records', to='vishi.vishi')),
            ],
            options={
                'ordering': ['-skipped_at'],
            },
        ),
    ]
