# Generated by Django 6.0.3 on 2026-03-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishi', '0002_alter_vishi_status_skiprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='vishi',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vishi',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
